
DROP TABLE USER;
DROP TABLE COMPANY;
DROP TABLE PAYMENT;

CREATE TABLE IF NOT EXISTS USER
(
    USER_ID        INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER_NAME      VARCHAR(100),
    USER_SEX       VARCHAR(1),
    USER_AGE       INT,
    USER_ID_NO     VARCHAR(18),
    USER_PHONE_NUM VARCHAR(11),
    USER_EMAIL     VARCHAR(100),
    CREATE_TIME    DATE DEFAULT CURRENT_TIMESTAMP,
    MODIFY_TIME    DATE DEFAULT CURRENT_TIMESTAMP,
    USER_STATE     VARCHAR(1),
    COMPANY_ID     INT
);

CREATE TABLE IF NOT EXISTS COMPANY
(
    COMPANY_ID    INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    COMPANY_NAME  VARCHAR(100),
    COMPANY_EMAIL VARCHAR(100),
    CREATE_TIME   DATE DEFAULT CURRENT_TIMESTAMP,
    MODIFY_TIME   DATE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PAYMENT
(
    PAYMENT_ID     INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PAYMENT_NAME   VARCHAR(100) COMMENT '缴费名字',
    PAYMENT_AMOUNT DOUBLE COMMENT '缴费金额',
    CREATE_TIME    DATE DEFAULT CURRENT_TIMESTAMP,
    MODIFY_TIME    DATE DEFAULT CURRENT_TIMESTAMP,
    USER_ID        INT
);