# https://docs.spring.io/spring-boot/docs/2.1.0.RELEASE/reference/html/common-application-properties.html

# server
server.port: 9090
#server.servlet.context-path: /sbw

# AOP
# 是否支持@EnableAspectJAutoProxy，默认为: true
spring.aop.auto: true
# true为使用CGLIB代理，需要自己引入jar包，false为JDK代理，默认为false
spring.aop.proxy-target-class: true

# JDBC
spring.datasource.url: jdbc:mysql://localhost:3306/sb-activiti-demo?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username: mysql01
spring.datasource.password: mysql01
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

# 请查看pom文件中的注解，说明 jdbc pool的使用顺序
# HikariCP settings
# spring.datasource.hikari.*

# 在 com.zaxxer.hikari.HikariConfig类中，能查看到很多属性及其默认值

#60 sec
spring.datasource.hikari.connection-timeout: 60000
# max 5
spring.datasource.hikari.maximum-pool-size: 5
# 连接检测
spring.datasource.hikari.connection-test-query: select 1

# mybatis
# mapper.xml所在的位置
mybatis.mapper-locations: classpath:mybatis/sqlmap/*.xml
# entity扫描的包名
mybatis.type-aliases-package: com.sauzny.sbactivitidemo.entity.pojo

# 打印sql
logging.level.com.sauzny.springbootweb.dao: debug

# pagehelper
pagehelper.helperDialect: mysql
pagehelper.reasonable: true
pagehelper.supportMethodsArguments: true
pagehelper.params: count=countSql