package com.sauzny.springmvc.entity.pojo;

import java.util.Date;

public class Ssq {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssq.id
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssq.qihao
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    private Integer qihao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssq.riqi
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    private Date riqi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssq.shunxu1
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    private Integer shunxu1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssq.shunxu2
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    private Integer shunxu2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssq.shunxu3
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    private Integer shunxu3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssq.shunxu4
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    private Integer shunxu4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssq.shunxu5
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    private Integer shunxu5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssq.shunxu6
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    private Integer shunxu6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssq.lan
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    private Integer lan;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssq.id
     *
     * @return the value of ssq.id
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssq.id
     *
     * @param id the value for ssq.id
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssq.qihao
     *
     * @return the value of ssq.qihao
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public Integer getQihao() {
        return qihao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssq.qihao
     *
     * @param qihao the value for ssq.qihao
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public void setQihao(Integer qihao) {
        this.qihao = qihao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssq.riqi
     *
     * @return the value of ssq.riqi
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public Date getRiqi() {
        return riqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssq.riqi
     *
     * @param riqi the value for ssq.riqi
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public void setRiqi(Date riqi) {
        this.riqi = riqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssq.shunxu1
     *
     * @return the value of ssq.shunxu1
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public Integer getShunxu1() {
        return shunxu1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssq.shunxu1
     *
     * @param shunxu1 the value for ssq.shunxu1
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public void setShunxu1(Integer shunxu1) {
        this.shunxu1 = shunxu1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssq.shunxu2
     *
     * @return the value of ssq.shunxu2
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public Integer getShunxu2() {
        return shunxu2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssq.shunxu2
     *
     * @param shunxu2 the value for ssq.shunxu2
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public void setShunxu2(Integer shunxu2) {
        this.shunxu2 = shunxu2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssq.shunxu3
     *
     * @return the value of ssq.shunxu3
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public Integer getShunxu3() {
        return shunxu3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssq.shunxu3
     *
     * @param shunxu3 the value for ssq.shunxu3
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public void setShunxu3(Integer shunxu3) {
        this.shunxu3 = shunxu3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssq.shunxu4
     *
     * @return the value of ssq.shunxu4
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public Integer getShunxu4() {
        return shunxu4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssq.shunxu4
     *
     * @param shunxu4 the value for ssq.shunxu4
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public void setShunxu4(Integer shunxu4) {
        this.shunxu4 = shunxu4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssq.shunxu5
     *
     * @return the value of ssq.shunxu5
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public Integer getShunxu5() {
        return shunxu5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssq.shunxu5
     *
     * @param shunxu5 the value for ssq.shunxu5
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public void setShunxu5(Integer shunxu5) {
        this.shunxu5 = shunxu5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssq.shunxu6
     *
     * @return the value of ssq.shunxu6
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public Integer getShunxu6() {
        return shunxu6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssq.shunxu6
     *
     * @param shunxu6 the value for ssq.shunxu6
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public void setShunxu6(Integer shunxu6) {
        this.shunxu6 = shunxu6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssq.lan
     *
     * @return the value of ssq.lan
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public Integer getLan() {
        return lan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssq.lan
     *
     * @param lan the value for ssq.lan
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public void setLan(Integer lan) {
        this.lan = lan;
    }
}