package com.sauzny.springmvc.entity.pojo;

public class TbUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.id
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.account
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.passwd
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.show_name
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    private String showName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.age
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.id
     *
     * @return the value of tb_user.id
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.id
     *
     * @param id the value for tb_user.id
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.account
     *
     * @return the value of tb_user.account
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.account
     *
     * @param account the value for tb_user.account
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.passwd
     *
     * @return the value of tb_user.passwd
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.passwd
     *
     * @param passwd the value for tb_user.passwd
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.show_name
     *
     * @return the value of tb_user.show_name
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public String getShowName() {
        return showName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.show_name
     *
     * @param showName the value for tb_user.show_name
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public void setShowName(String showName) {
        this.showName = showName == null ? null : showName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.age
     *
     * @return the value of tb_user.age
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.age
     *
     * @param age the value for tb_user.age
     *
     * @mbg.generated Fri Sep 01 17:11:42 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}